/* Untyped file generated by genType. */

import * as AddFormBS from './AddForm.bs';

import * as ReasonReact from 'reason-react/src/ReasonReact.js';

export const AddForm = ReasonReact.wrapReasonForJs(
  AddFormBS.component,
  (function _(jsProps) {
     return AddFormBS.make(jsProps.children);
  }));

export default AddForm;
