/* Untyped file generated by genType. */

import * as HomeBS from './Home.bs';

import * as ReasonReact from 'reason-react/src/ReasonReact.js';

export const Home = ReasonReact.wrapReasonForJs(
  HomeBS.component,
  (function _(jsProps) {
     return HomeBS.make(jsProps.children);
  }));

export default Home;
